# Generated by Django 4.2.2 on 2024-03-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField()),
                ('table_no', models.BigIntegerField()),
                ('Item_Name', models.CharField(max_length=100, null=True)),
                ('unit_Price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField()),
                ('table_no', models.BigIntegerField()),
                ('Customer_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('Total', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField()),
                ('table_no', models.BigIntegerField()),
                ('customer_name', models.CharField(max_length=250, null=True)),
                ('customer_mobile_number', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.BigIntegerField(default=0)),
                ('Item_Name', models.CharField(max_length=100)),
                ('unit_Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('alternate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=128)),
                ('valid_upto', models.DateField()),
                ('payment', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
